stepshop/adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    # path('users/read/', adminapp.users, name='users'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),

]

stepshop/authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

stepshop/stepshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/adminapp/models.py
from django.db import models

# Create your models here.

stepshop/adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from django.contrib.auth.forms import UserChangeForm


class ShopUserAdminEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'is_superuser', 'is_staff', 'is_active', 'is_deleted',
                  'first_name', 'last_name', 'email', 'age', 'avatar')
        # fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.help_text = ''

stepshop/adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic.list import ListView

from adminapp.forms import ShopUserAdminEditForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory


def user_create(request):
    title = "админка | пользователи | создать"

    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)

        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin_staff:users'))
    else:
        user_form = ShopUserRegisterForm()

    context = {
        'title': title,
        'user_form': user_form,
    }

    return render(request, 'adminapp/user_create.html', context)


# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     title = "админка | пользователи"
#
#     users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
#
#     context = {
#         'title': title,
#         'objects': users_list,
#     }
#
#     return render(request, 'adminapp/users.html', context)


class UsersListView(UserPassesTestMixin, ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    context_object_name = 'objects'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UsersListView, self).get_context_data()
        context['title'] = "админка | пользователи"
        # context.update({'title': "админка | пользователи"})
        return context

    def get_queryset(self):
        return ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')

    def test_func(self):
        return self.request.user.is_superuser


def user_update(request, pk):
    title = "админка | пользователи | редактировать"

    edit_user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)

        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin_staff:users'))
    else:
        edit_form = ShopUserAdminEditForm(instance=edit_user)

    context = {
        'title': title,
        'edit_form': edit_form,
    }

    return render(request, 'adminapp/user_update.html', context)


def user_delete(request, pk):
    title = "админка | пользователи | удалить"

    user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        user.is_deleted = True
        user.save()
        return HttpResponseRedirect(reverse('admin_staff:users'))

    context = {
        'title': title,
        'user_to_delete': user,
    }

    return render(request, 'adminapp/user_delete.html', context)


def category_create(request):
    pass


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = "админка | категории"

    categories_list = ProductCategory.objects.all()

    context = {
        'title': title,
        'objects': categories_list,
    }

    return render(request, 'adminapp/categories.html', context)


def category_update(request):
    pass


def category_delete(request):
    pass


def product_create(request):
    pass


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = "админка | продукты"

    category = get_object_or_404(ProductCategory, pk=pk)
    products_list = Product.objects.filter(category__pk=pk)

    context = {
        'title': title,
        'objects': products_list,
        'category': category,
    }

    return render(request, 'adminapp/products.html', context)


def product_read(request):
    pass


def product_update(request):
    pass


def product_delete(request):
    pass

stepshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'adminapp/style.css' %}">
        <link rel="stylesheet" type="text/css" href='https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css'>
        <link rel="stylesheet" type="text/css" href="{% static 'stepshop/assets/css/fontawesome.css' %}">

    {% block css %}
    {% endblock %}

    <script src="{% static 'adminapp/script.js' %}"></script>

    {% block js %}
    {% endblock %}
</head>
<body id="body-pd">
<header class="header" id="header">
    <div class="header_toggle"><i class='bx bx-menu' id="header-toggle"></i></div>
    <div class="header_img"><img src="/media/{{ user.avatar|default:'avatar-default.png' }}" alt=""></div>
</header>
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="{% url 'index' %}" class="nav_logo">
                <i class='bx bx-layer nav_logo-icon'></i>
                <span class="nav_logo-name">Admin`ka</span>
            </a>
            {% include 'adminapp/inludes/inc_admin_menu.html' %}
        </div>
        <a href="{% url 'auth:login' %}" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Выход</span> </a>
    </nav>
</div>
<!--Container Main start-->
<div class="height-100 bg-light">
    {% block content %}
    {% endblock %}
</div>
<!--Container Main end-->
</body>
</html>

stepshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Категории</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Категории продуктов
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for category in objects %}
                            <tr {% if category.is_deleted %} style="opacity: 0.5;" {% endif %}>
                                <td><a href="{% url 'admin_staff:products' category.pk %}" style="color: dodgerblue">
                                    {{ category.name }}</a></td>
                                <td>
                                    <a {% if category.is_deleted %} class="invisible" {% endif %}
                                       href="{% url 'admin_staff:category_update' pk=category.pk%}">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                </td>
                                <td>
                                    <a {% if category.is_deleted %} class="invisible" {% endif %}
                                       href="{% url 'admin_staff:category_delete' pk=category.pk %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:category_create' %}">
                    <button class="btn btn-success">Создать категорию</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

stepshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}

    <div class="container-fluid">
        <h1 class="mt-4">Продукты
            {% if category %}
                :<span>{{ category.name }}</span>
            {% endif %}
        </h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fa fa-table mr-1"></i>
                <a href="{% url 'admin_staff:categories' %}">Категории</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Изображение</th>
                            <th>Имя</th>
                            <th>Описание</th>
                            <th>Количество</th>
                            <th>Цена</th>
                            <th>Подробнее</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Изображение</th>
                            <th>Имя</th>
                            <th>Описание</th>
                            <th>Количество</th>
                            <th>Цена</th>
                            <th>Подробнее</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                            {% for object in objects %}
                                <tr>
                                <td><img src="{{ object.image|media_folder_products }}"
                                  alt="{{ object.name }}" style="width:50px;">
                                </td>
                                <td>
                                  {{ object.name|title }}
                                </td>
                                <td>
                                  {{ object.short_desc|title }}
                                </td>
                                <td>{{ object.quantity }}</td>
                                <td>{{ object.price }} руб</td>
                                <td>
                                  <button type="button" class="btn btn-primary">
                                    <a class="text-white" href="{% url 'admin_staff:product_read' object.pk %}">
                                      подробнее
                                    </a>
                                  </button>
                                </td>
                                <td>
                                  <button class="btn btn-warning">
                                    <a class="text-dark" href="{% url 'admin_staff:product_update' object.pk %}">
                                      редактировать
                                    </a>
                                  </button>
                                    </td>
                                <td>
                                  <button class="btn btn-danger">
                                    <a class="text-white" href="{% url 'admin_staff:product_delete' object.pk %}">
                                      удалить
                                    </a>
                                  </button>
                                </td>
                                </tr>
                            {% endfor%}
                        </tbody>
                    </table>

            <div class="card-footer">
                <button class="btn btn-success">
                  <a class="text-white" href="{% url 'admin_staff:product_create' category.pk %}">
                    новый продукт
                  </a>
                </button>
            </div>

  </div>

{% endblock %}

stepshop/adminapp/templates/adminapp/user_create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="mx-auto col-3">
        <form class="form-horizontal" action="{% url 'admin_staff:user_create' %}"
              method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            <input class="btn btn-primary" type="submit" value="Создать">
        </form>
    </div>
{% endblock %}

stepshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="mx-auto col-3">
        Уверенны, что хотите удалить {{ user_to_delete.username }}
        {% if user_to_delete.first_name %}
            ({{ user_to_delete.first_name|title }}
            {% if user_to_delete.last_name %}
                {{ user_to_delete.last_name|title }}
            {% endif %})
        {% endif %}?

        <form action="{% url 'admin_staff:user_delete' user_to_delete.pk %}"
              class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input class="btn btn-primary" type="submit" value="Удалить">

            <button class="btn btn-primary">
                <a class="link-light" href="{% url 'admin_staff:users' %}">
                    Отмена
                </a>
            </button>
        </form>
    </div>
{% endblock %}

stepshop/adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="mx-auto col-3">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ edit_form.as_p }}
            <input class="btn btn-primary" type="submit" value="Сохранить">
        </form>
    </div>
{% endblock %}

stepshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Пользователи
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for user in objects %}
                            <tr {% if not user.is_active %} style="opacity: 0.5;" {% endif %}>
                                <td><a href="{% url 'admin_staff:user_update' user.id %}" style="color: dodgerblue">
                                    {{ user.username }}</a></td>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.last_name }}</td>
                                <td>{{ user.email }}</td>
                                <td class="text-center">
                                    {% if user.is_staff %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if user.is_active %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td>{{ user.last_login }}</td>
                                <td>
                                    <a {% if not user.is_active %} class="invisible" {% endif %}
                                       href="{% url 'admin_staff:user_delete' pk=user.id %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:user_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}