stepshop/authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

stepshop/basketapp/urls.py
from django.urls import path

from basketapp.views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit'),
    path('remove/<int:pk>/', basket_remove, name='remove'),
]

stepshop/mainapp/urls.py
from django.urls import path

from .views import products, product

app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('page/<int:page>/', products, name='page'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='category_page'),
    path('product/<int:pk>/', product, name='product'),
]

stepshop/stepshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name or f'Категория с id - {self.pk}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='категория',
    )

    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )

    image = models.ImageField(
        upload_to='product_images',
        blank=True,
        verbose_name='изображение',
    )

    short_desc = models.CharField(
        verbose_name='краткое описание',
        max_length=128,
        blank=True,
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    price = models.DecimalField(
        verbose_name='цена',
        max_digits=8,
        decimal_places=2,
        default=0,
    )

    quantity = models.PositiveIntegerField(
        verbose_name='количество товара на сладе',
        default=0,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name or f'Продукт с id - {self.pk}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

stepshop/mainapp/views.py
import random

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from basketapp.models import Basket
from mainapp.models import Product, ProductCategory


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    return []


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def get_same_product(product):
    same_products = Product.objects.filter(category=product.category).exclude(pk=product.pk)
    return same_products


def products(request, pk=None, page=1):
    title = 'продукты'

    links_menu = [
        {'href': 'index', 'name': 'Главная', 'route': ''},
        {'href': 'products:index', 'name': 'Продукты', 'route': 'products/'},
        # {'href': 'about', 'name': 'О&nbsp;нас', 'route': 'about/'},
        {'href': 'contacts', 'name': 'Контакты', 'route': 'contacts/'},
    ]

    products = Product.objects.filter(is_deleted=False)
    categories = ProductCategory.objects.all()
    basket = get_basket(request.user)
    category = {'name': 'все'}

    if pk is not None:
        category = get_object_or_404(ProductCategory, pk=pk)
        products = Product.objects.filter(is_deleted=False, category__pk=pk).order_by('price')

        if category.is_deleted:
            return HttpResponseRedirect(reverse('products:index'))

    paginator = Paginator(products, 3)

    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    context = {
        'title': title,
        'links_menu': links_menu,
        'products': products_paginator,  # 'products': products,
        'categories': categories,
        'pk': pk,
        'category': category,
        'basket': basket,
    }

    return render(request, 'mainapp/products.html', context)


def product(request, pk):
    title = 'продукт'

    links_menu = [
        {'href': 'index', 'name': 'Главная', 'route': ''},
        {'href': 'products:index', 'name': 'Продукты', 'route': 'products/'},
        # {'href': 'about', 'name': 'О&nbsp;нас', 'route': 'about/'},
        {'href': 'contacts', 'name': 'Контакты', 'route': 'contacts/'},
    ]

    # links_menu = ProductCategory.objects.all()
    product_item = get_object_or_404(Product, pk=pk)

    category = product_item.category
    basket = get_basket(request.user)

    same_products = get_same_product(product_item)

    # if not category.is_active or not product_item.is_active:
    #     return HttpResponseRedirect(reverse('products:index'))

    context = {
        'title': title,
        'links_menu': links_menu,
        'product': product_item,
        'category': category,
        'same_products': same_products,
        'basket': basket,
    }

    return render(request, 'mainapp/product.html', context)

stepshop/mainapp/templates/mainapp/product.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    <!-- Page Content -->
    <!-- Single Starts Here -->
    <div class="single-product">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>{{ product }}</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div class="product-slider">
              <div id="slider" class="flexslider">
                {#% if product.image %#}
                <img src="{{ product.image|media_folder_products }}"
                     alt="{{ product.name }}"
                     title="{{ product.name }}"
                     class="img-fluid">
                {#% endif %#}
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <h4>{{ product.name }}</h4>
              <h6>${{ product.price|floatformat:"0g" }}</h6>
              <p>{{ product.description }}</p>

              <div class="main-button">
                <a href="{% url 'basket:add' product.pk %}">Заказать</a>
              </div>

              <div class="down-content">
                <div class="categories">
                  <h6>Категория: <span>{{ category }}</span></h6>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Single Page Ends Here -->


    <!-- Similar Starts Here -->
    <div class="featured-items">
      <div class="container">
        <div class="row">

          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Похожие продукты</h1>
            </div>
          </div>

          <div class="col-md-12">
            <div class="owl-carousel owl-theme">

              {% for product in same_products %}
              <a href="{% url 'products:product' product.pk %}">
                <div class="featured-item">
                  <img src="{{ product.image|media_folder_products }}"
                     alt="{{ product.name }}"
                     title="{{ product.name }}"
                     class="img-fluid">
                  <h4>{{ product.name|capfirst }}</h4>
                  <h6>${{ product.price|floatformat:"0g" }}</h6>
                </div>
              </a>
              {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Similar Ends Here -->
{% endblock %}

stepshop/mainapp/templates/mainapp/products.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
<!-- Page Content -->
<!-- Items Starts Here -->
{% include 'mainapp/includes/inc_category_menu.html' %}

<div class="featured container no-gutter">

    <div class="row posts">

        {% for product in products %}

        <div id="{{ product.pk }}" class="item new col-md-4">
            <a href="{% url 'products:product' product.pk %}">
                <div class="featured-item">
                    <img src="{{ product.image|media_folder_products }}"
                         alt="{{ product.name }}">
                    <h4>{{ product.name|capfirst }}</h4>
                    <h6>${{ product.price|floatformat:"0g" }}</h6>
                </div>
            </a>
        </div>

        {% endfor %}

    </div>
</div>

{% if products.paginator and products.paginator.num_pages > 1 %}
<div class="page-navigation">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul>
                    {% if products.has_previous %}
                    <li><a href="
                    {% if pk %}
                        {% url 'products:category_page' category.pk products.previous_page_number %}
                    {% else %}
                        {% url 'products:page' products.previous_page_number %}
                    {% endif %}
                                ">
                        <i class="fa fa-angle-left"></i></a></li>
                    {% endif %}

                    {% for page in products.paginator.page_range %}

                        <li {% if products.number == page %}
                                class="current-page"
                            {% endif %}>
                            <a href="
                                {% if pk %}
                                    {% url 'products:category_page' category.pk page %}
                                {% else %}
                                    {% url 'products:page' page %}
                                {% endif %}
                                    ">
                                {{ page }}
                            </a>
                        </li>

                    {% endfor %}

                    {% if products.has_next %}
                    <li><a href="
                    {% if pk %}
                        {% url 'products:category_page' category.pk products.next_page_number %}
                    {% else %}
                        {% url 'products:page' products.next_page_number %}
                    {% endif %}
                                ">
                        <i class="fa fa-angle-right"></i></a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endif %}
<!-- Featred Page Ends Here -->
{% endblock %}